default_language_version:
  python: python3.8

repos:
  # Out-of-the-box hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files # Prevent giant files from being committed (default 500kb)
      - id: check-docstring-first # Checks for a common error of placing code before the docstring
      - id: check-json # Attempts to load all json files to verify syntax
      - id: check-merge-conflict # Check for files that contain merge conflict strings
      - id: check-symlinks # Checks for sym links which do not point to anything
      - id: check-toml # Attempts to load all TOML files to verify syntax
      - id: check-yaml # Attempts to load all yaml files to verify syntax
      - id: end-of-file-fixer # Makes sure files end in a newline and only a newline
      - id: no-commit-to-branch # Protect specific branches from direct push (forbids commit push to `main` by default)
      - id: requirements-txt-fixer # Sorts entries in requirements.txt and removes incorrect entries
      - id: trailing-whitespace # Trims trailing whitespace
  # Automatically upgrade syntax
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
      - id: pyupgrade
        args: ["--py38-plus"]
  - repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
      - id: black
        language_version: python3.8
  # Linting
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  # Sorting imports
  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
