[tool.black]
target_version = ["py38"]
experimental-string-processing = true

[tool.isort]
profile = "black"

[tool.mypy]
exclude = "(venv/|.venv/)"
python_version = 3.8
disallow_any_unimported = true
disallow_any_explicit = false
disallow_any_generics = true
disallow_subclassing_any = true
disallow_untyped_calls = false # There is a bug when set to true with Numpy: https://github.com/python/mypy/issues/10757
disallow_untyped_defs = true
disallow_incomplete_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
warn_unreachable = true
strict_equality = true
show_error_codes = true

[[tool.mypy.overrides]]
module = [
    "plotly.*",
    "sklearn.metrics"
]
ignore_missing_imports = true


[tool.pytest.ini_options]
addopts = "-s -p no:warnings --import-mode=importlib"
log_cli = 1
log_cli_level = "INFO"
log_cli_format = "[pytest][%(asctime)s][%(levelname)s][%(module)s][%(funcName)s] %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
log_level = "INFO"
testpaths = [
    "deployment/unit_tests",
    "deployment/integration_tests",
]
pythonpath = "."

[tool.coverage.run]
omit = [
    "**/{{cookiecutter.project_slug_under}}/data_science/*"
]
